---

# Install Docker and dependencies

- name: Install Docker dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - apt-transport-https
   - ca-certificates 
   - curl
   - gnupg
   - software-properties-common 
   - lsb-release

- name: Dockers official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
#    updat_cache: yes

- name: Install Docker engine and dependencies
  apt: name={{ item }} state=present
  with_items:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   - docker-compose-plugin

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
